compressionLevel: 0

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableImmutableInstalls: false

enableInlineBuilds: true

enableProgressBars: false

nodeLinker: node-modules
